version: '3'
services:
  db:
    image: postgres:14.4-bullseye
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - ./myapp:/myapp
    depends_on:
      - db
    command: /bin/bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
volumes:
  postgres_data: